# Generated by Django 5.2.13 on 2026-04-21 05:42

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qapair',
            name='question_embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
    ]
