# Generated by Django 5.2.13 on 2026-04-21 05:45

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_qapair_question_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qapair',
            name='question_embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
