# Generated by Django 5.2.13 on 2026-04-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_qapair_question_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='qapair',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='qapair',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
