# Generated by Django 5.2.13 on 2026-04-21 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_qapair_is_verified_qapair_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('up', '좋음'), ('down', '나쁨')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('qa_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chat.qapair')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
