# Generated by Django 5.2.13 on 2026-04-21 06:37

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='qa_pair',
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('answer', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['question_embedding'], m=16, name='chatlog_q_emb_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='CanonicalQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('answer', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_chatlog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='chat.chatlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='chat_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chat.chatlog'),
        ),
        migrations.DeleteModel(
            name='QAPair',
        ),
        migrations.AddIndex(
            model_name='canonicalqa',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['question_embedding'], m=16, name='canonical_q_emb_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
