# Generated by Django 5.2.13 on 2026-04-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_routerrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerrule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routerrule',
            name='enabled',
            field=models.BooleanField(default=True, help_text='체크를 풀면 이 규칙을 무시합니다.\n(삭제하지 않고 잠시 꺼두는 용도)'),
        ),
        migrations.AlterField(
            model_name='routerrule',
            name='match_type',
            field=models.CharField(choices=[('contains', '포함 (contains)')], default='contains', help_text='키워드를 질문과 어떻게 비교할지 정합니다.\n\n• 포함 — 질문 안에 키워드가 조각으로라도 들어 있으면 매치\n• 정확히 일치 — 질문이 키워드와 글자 그대로 똑같을 때만 매치\n• 정규식 — 키워드를 패턴 문법으로 해석해 매치\n• 제외 — 이 키워드가 있으면 오히려 규칙을 적용하지 않음', max_length=20),
        ),
        migrations.AlterField(
            model_name='routerrule',
            name='name',
            field=models.CharField(help_text='이 규칙을 알아볼 수 있는 이름을 적어주세요.\n예) "며칠 질문 보강", "복지포인트 오분류 제외"', max_length=100),
        ),
        migrations.AlterField(
            model_name='routerrule',
            name='pattern',
            field=models.CharField(help_text='질문에 포함되어 있으면 규칙이 걸리는 단어/문구를 적으세요.\n예) "퇴직금" → "퇴직금 얼마야?" 매치\n\n※ 앞뒤에 /, #, 따옴표 같은 기호를 붙이지 마세요.\n※ 띄어쓰기도 그대로 비교합니다 ("연차 계산"과 "연차계산"은 다름).\n※ 변형이 많으면 짧게 쪼개서 여러 규칙으로 등록하는 편이 안전합니다.', max_length=256),
        ),
        migrations.AlterField(
            model_name='routerrule',
            name='priority',
            field=models.IntegerField(default=100, help_text='숫자가 클수록 먼저 평가됩니다.\n• 일반 규칙: 100\n• 반드시 우선 적용할 규칙: 200 이상'),
        ),
        migrations.AlterField(
            model_name='routerrule',
            name='route',
            field=models.CharField(choices=[('single_shot', 'single-shot'), ('workflow', 'workflow'), ('agent', 'agent')], help_text='이 규칙에 걸린 질문을 어떤 방식으로 처리할지 선택하세요.\n• single-shot — 바로 답변\n• workflow — 정해진 계산 흐름\n• agent — 상황 판단·비교', max_length=20),
        ),
    ]
