# Generated by Django 5.2.13 on 2026-04-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_routerrule_workflow_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='purpose',
            field=models.CharField(db_index=True, default='unknown', max_length=32),
        ),
    ]
