# Generated by Django 5.2.13 on 2026-04-20 00:27

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', '대기'), ('processing', '처리중'), ('ready', '준비완료'), ('failed', '실패')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='files.document')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='doc_chunk_emb_hnsw', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='doc_chunk_unique_idx')],
            },
        ),
    ]
