# Generated by Django 5.2.13 on 2026-04-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='edited_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('reviewing', '검토대기'), ('processing', '처리중'), ('ready', '준비완료'), ('failed', '실패')], db_index=True, default='pending', max_length=20),
        ),
    ]
