"""
Django settings for AI_Chat project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 프롬프트 파일 루트. 기본은 repo 내부 assets/prompts/, 운영에서는 PROMPTS_DIR
# 환경변수로 외부 마운트 경로를 줘서 재배포 없이 교체 가능.
PROMPTS_DIR = Path(os.environ.get('PROMPTS_DIR', BASE_DIR / 'assets' / 'prompts'))


# 환경변수 헬퍼
def _env_bool(name: str, default: bool) -> bool:
    """문자열 env 를 bool로. true/1/yes/on 만 참으로 본다."""
    v = os.environ.get(name)
    if v is None:
        return default
    return v.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name: str, default: list) -> list:
    """쉼표 구분 env 를 리스트로. 공백/빈 원소는 제거."""
    raw = os.environ.get(name)
    if not raw:
        return default
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 환경변수 DJANGO_SECRET_KEY에서 로드. 없으면 즉시 에러 (코드에 키를 남기지 않기 위함).
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
# 기본값 False — 운영 안전. 로컬 개발은 .env 에 DJANGO_DEBUG=True 명시.
DEBUG = _env_bool('DJANGO_DEBUG', False)

# DEBUG=True 면 모든 호스트 허용(개발 편의), False 면 env 에서 명시 필요.
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', ['*'] if DEBUG else [])

# 리버스 프록시 뒤에서 HTTPS 로 들어오는 도메인을 CSRF 신뢰 목록에 등록.
# 스킴 포함 전체 URL 로 지정 (예: https://your-domain.example).
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS', [])

# 채팅 파이프라인을 LangGraph 기반 진입점으로 실행할지 여부 (2.0.0 Phase 2).
# 기본 True — dev/운영 모두 새 경로로 운영해 이슈를 조기에 발견.
# 운영에서 문제 발생 시 .env 에 USE_LANGGRAPH_PIPELINE=False 만 설정하고 재기동하면
# 이전 direct 호출 경로로 즉시 롤백된다. Phase 3 에서 feature flag 는 제거 예정.
USE_LANGGRAPH_PIPELINE = _env_bool('USE_LANGGRAPH_PIPELINE', True)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 로컬 앱
    'chat',
    'bo',
    'files',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise — gunicorn 프로세스가 직접 정적파일 서빙 (nginx 없이도 동작)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AI_Chat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AI_Chat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'mydb'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'password'),
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# collectstatic 결과물 위치. WhiteNoise 가 여기서 서빙.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise 압축·캐시 스토리지 (Django 4.2+ STORAGES 형식)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# 업로드 파일 (회사 자료 등)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'resources'

# 같은 도메인의 iframe 허용 (PDF 미리보기 모달용)
X_FRAME_OPTIONS = 'SAMEORIGIN'

# ─── 리버스 프록시 뒤에서 HTTPS 인식 ──────────────────────
# 프록시가 X-Forwarded-Proto: https 헤더를 넣어주면 Django가 HTTPS 로 인식.
# DEBUG=False 에서만 활성화 (로컬 http 개발 시 불필요).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    # HTTPS 뒤라면 쿠키도 Secure 로
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
